### ISSUE TITLE
Minor changes

### ISSUE THREAD

**Issue by craigmediaservices** [bug-or-feature/bc-utils#13]
It appears Mr. Carver changed "init_db_with_csv_futures_contract_prices" to "init_arctic_with_csv_futures_contract_prices" at some point, so the sample in the ReadMe doesn't work.

Additionally the code will seed mongo with prices like "Day_AEX" and "Hour_AEX" based on the CSV file names, which wont work with the various other config files, roll calendars, etc.

I'm not familiar enough with the actual backend (pysystemtrade) to sort how to tell it to store both under the same symbol.

**Comment by bug-or-feature** [comment]
@craigmediaservices hi thanks for your interest in the project

> It appears Mr. Carver changed "init_db_with_csv_futures_contract_prices" to "init_arctic_with_csv_futures_contract_prices" at some point, so the sample in the ReadMe doesn't work.

no, it's the other way around. it used be called *arctic* but was renamed when he moved from arctic to parquet.  perhaps you are looking at an older version?

> Additionally the code will seed mongo with prices like "Day_AEX" and "Hour_AEX" based on the CSV file names, which wont work with the various other config files, roll calendars, etc.

If you are seeing mongo records with names like that, then you are not importing the prices correctly. The code for importing split frequency prices is commented at the bottom of `contract_prices_from_csv_to_arctic.py`. I haven't updated the README, because the current solution for importing split frequency prices is not quite right in Rob's project. I have fixed it in my own fork, but not pushed to upstream yet. I'll get round to it - but you can find it here if you're in a rush

https://github.com/bug-or-feature/pysystemtrade-fsb/blob/dev/sysinit/futures/contract_prices_from_split_freq_csv_to_db.py

**Comment by craigmediaservices** [comment]
I'm sorry, thank you so much. I am out of date and was unaware of the switch to parquet.

I have been working on getting pysystemtrade fully running for a lot longer than I realized, lol.

**Comment by bug-or-feature** [comment]
There have been quite a lot of big changes to pysystemtrade that have not really made it to the docs. See [here](https://github.com/robcarver17/pysystemtrade/blob/develop/docs/recent_changes.md) 

Good luck!

**Comment by craigmediaservices** [comment]
Hopefully this doesn't reopen, just wanted to make a quick comment.

I was having issues trying to use the config setup from the README.md, but had to change the format from "%Y-%m-%dT%H:%M:%S%z" to "%Y-%m-%dT%H:%M:%S" to run the import which I'm not sure why - it ran fine with the old version of PySystemTrade and your sample code!

Also, with your updated .py (that looks great, thank you for sharing!) instrument_codes kept returning empty. I can pull them with the commented lines in contract_prices_from_csv_to_arctic.py by specifying frequency though - thank you for pointing those out!

In the end, everything was finally imported though. I appreciate all your help.
